services:
  x-panel:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: x-panel_app
    # hostname: yourhostname <<--- optional
    volumes:
      - $PWD/db/:/etc/makex-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
    tty: true
    network_mode: host
    restart: unless-stopped
